/**
 * TOPIK Master Vocabulary Dataset (Enriched with Sino-Vietnamese Hán-Việt Roots)
 * Generated automatically by local background worker.
 * Clean, verified vocabulary entries.
 */

export interface TopikVocabularyItem {
  id: string
  ko: string
  vi: string
  en: string
  level: number
  sinoVi?: string
  category: string
  pronunciation?: string
  created_at?: string
}

export const TOPIK_VOCABULARY_DATA: TopikVocabularyItem[] = [
  {
    "id": "v1-1-학생",
    "ko": "학생",
    "vi": "Học sinh",
    "en": "Student",
    "level": 1,
    "sinoVi": "Học sinh",
    "category": "academic",
    "pronunciation": "[학생]",
    "created_at": "2026-08-10T02:20:02.673Z"
  },
  {
    "id": "v1-2-학교",
    "ko": "학교",
    "vi": "Trường học",
    "en": "School",
    "level": 1,
    "sinoVi": "Học hiệu",
    "category": "academic",
    "pronunciation": "[학교]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-3-선생님",
    "ko": "선생님",
    "vi": "Thầy/Cô giáo",
    "en": "Teacher",
    "level": 1,
    "sinoVi": "Tiên sinh",
    "category": "academic",
    "pronunciation": "[선생님]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-4-도서관",
    "ko": "도서관",
    "vi": "Thư viện",
    "en": "Library",
    "level": 1,
    "sinoVi": "Đồ thư quán",
    "category": "academic",
    "pronunciation": "[도서관]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-5-책",
    "ko": "책",
    "vi": "Sách",
    "en": "Book",
    "level": 1,
    "category": "academic",
    "pronunciation": "[책]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-6-공부",
    "ko": "공부",
    "vi": "Học tập",
    "en": "Study",
    "level": 1,
    "sinoVi": "Công",
    "category": "academic",
    "pronunciation": "[공부]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-7-친구",
    "ko": "친구",
    "vi": "Bạn bè",
    "en": "Friend",
    "level": 1,
    "sinoVi": "Cứu",
    "category": "daily",
    "pronunciation": "[친구]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-8-가족",
    "ko": "가족",
    "vi": "Gia đình",
    "en": "Family",
    "level": 1,
    "sinoVi": "Gia tộc",
    "category": "daily",
    "pronunciation": "[가족]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-9-아버지",
    "ko": "아버지",
    "vi": "Bố, Cha",
    "en": "Father",
    "level": 1,
    "sinoVi": "Địa",
    "category": "daily",
    "pronunciation": "[아버지]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-10-어머니",
    "ko": "어머니",
    "vi": "Mẹ",
    "en": "Mother",
    "level": 1,
    "category": "daily",
    "pronunciation": "[어머니]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-11-형",
    "ko": "형",
    "vi": "Anh trai (nam gọi)",
    "en": "Older brother (male speaker)",
    "level": 1,
    "category": "daily",
    "pronunciation": "[형]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-12-누나",
    "ko": "누나",
    "vi": "Chị gái (nam gọi)",
    "en": "Older sister (male speaker)",
    "level": 1,
    "category": "daily",
    "pronunciation": "[누나]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-13-오빠",
    "ko": "오빠",
    "vi": "Anh trai (nữ gọi)",
    "en": "Older brother (female speaker)",
    "level": 1,
    "category": "daily",
    "pronunciation": "[오빠]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-14-언니",
    "ko": "언니",
    "vi": "Chị gái (nữ gọi)",
    "en": "Older sister (female speaker)",
    "level": 1,
    "category": "daily",
    "pronunciation": "[언니]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-15-동생",
    "ko": "동생",
    "vi": "Em (em trai/em gái)",
    "en": "Younger sibling",
    "level": 1,
    "sinoVi": "Động Sinh",
    "category": "daily",
    "pronunciation": "[동생]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-16-집",
    "ko": "집",
    "vi": "Nhà",
    "en": "House/Home",
    "level": 1,
    "category": "daily",
    "pronunciation": "[집]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-17-방",
    "ko": "방",
    "vi": "Phòng",
    "en": "Room",
    "level": 1,
    "category": "daily",
    "pronunciation": "[방]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-18-식당",
    "ko": "식당",
    "vi": "Nhà hàng, Quán ăn",
    "en": "Restaurant",
    "level": 1,
    "sinoVi": "Thực đường",
    "category": "daily",
    "pronunciation": "[식당]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-19-음식",
    "ko": "음식",
    "vi": "Thức ăn, Món ăn",
    "en": "Food",
    "level": 1,
    "sinoVi": "Ẩm thực",
    "category": "daily",
    "pronunciation": "[음식]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-20-물",
    "ko": "물",
    "vi": "Nước",
    "en": "Water",
    "level": 1,
    "sinoVi": "Vật",
    "category": "daily",
    "pronunciation": "[물]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-21-밥",
    "ko": "밥",
    "vi": "Cơm",
    "en": "Rice / Meal",
    "level": 1,
    "category": "daily",
    "pronunciation": "[밥]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-22-빵",
    "ko": "빵",
    "vi": "Bánh mì",
    "en": "Bread",
    "level": 1,
    "category": "daily",
    "pronunciation": "[빵]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-23-우유",
    "ko": "우유",
    "vi": "Sữa",
    "en": "Milk",
    "level": 1,
    "category": "daily",
    "pronunciation": "[우유]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-24-커피",
    "ko": "커피",
    "vi": "Cà phê",
    "en": "Coffee",
    "level": 1,
    "category": "daily",
    "pronunciation": "[커피]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-25-사과",
    "ko": "사과",
    "vi": "Quả táo",
    "en": "Apple",
    "level": 1,
    "sinoVi": "Sư",
    "category": "daily",
    "pronunciation": "[사과]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-26-시계",
    "ko": "시계",
    "vi": "Đồng hồ",
    "en": "Watch / Clock",
    "level": 1,
    "sinoVi": "Thị Kế",
    "category": "daily",
    "pronunciation": "[시계]",
    "created_at": "2026-08-10T02:20:02.676Z"
  },
  {
    "id": "v1-27-전화",
    "ko": "전화",
    "vi": "Điện thoại",
    "en": "Phone",
    "level": 1,
    "sinoVi": "Điện Hóa",
    "category": "daily",
    "pronunciation": "[전화]",
    "created_at": "2026-08-10T02:20:02.677Z"
  },
  {
    "id": "v1-28-컴퓨터",
    "ko": "컴퓨터",
    "vi": "Máy tính",
    "en": "Computer",
    "level": 1,
    "category": "daily",
    "pronunciation": "[컴퓨터]",
    "created_at": "2026-08-10T02:20:02.677Z"
  },
  {
    "id": "v1-29-옷",
    "ko": "옷",
    "vi": "Quần áo",
    "en": "Clothes",
    "level": 1,
    "category": "shopping",
    "pronunciation": "[옷]",
    "created_at": "2026-08-10T02:20:02.677Z"
  },
  {
    "id": "v1-30-신발",
    "ko": "신발",
    "vi": "Giày dép",
    "en": "Shoes",
    "level": 1,
    "category": "shopping",
    "pronunciation": "[신발]",
    "created_at": "2026-08-10T02:20:02.677Z"
  },
  {
    "id": "v1-31-가방",
    "ko": "가방",
    "vi": "Cặp, Túi xách",
    "en": "Bag",
    "level": 1,
    "sinoVi": "Gia",
    "category": "shopping",
    "pronunciation": "[가방]",
    "created_at": "2026-08-10T02:20:02.677Z"
  },
  {
    "id": "v1-32-돈",
    "ko": "돈",
    "vi": "Tiền",
    "en": "Money",
    "level": 1,
    "category": "shopping",
    "pronunciation": "[돈]",
    "created_at": "2026-08-10T02:20:02.677Z"
  },
  {
    "id": "v1-33-시장",
    "ko": "시장",
    "vi": "Chợ",
    "en": "Market",
    "level": 1,
    "sinoVi": "Thị Trường",
    "category": "shopping",
    "pronunciation": "[시장]",
    "created_at": "2026-08-10T02:20:02.677Z"
  },
  {
    "id": "v1-34-마트",
    "ko": "마트",
    "vi": "Siêu thị",
    "en": "Mart",
    "level": 1,
    "category": "shopping",
    "pronunciation": "[마트]",
    "created_at": "2026-08-10T02:20:02.677Z"
  },
  {
    "id": "v1-35-병원",
    "ko": "병원",
    "vi": "Bệnh viện",
    "en": "Hospital",
    "level": 1,
    "sinoVi": "Bệnh viện",
    "category": "hospital",
    "pronunciation": "[병원]",
    "created_at": "2026-08-10T02:20:02.677Z"
  },
  {
    "id": "v1-36-약국",
    "ko": "약국",
    "vi": "Tiệm thuốc",
    "en": "Pharmacy",
    "level": 1,
    "sinoVi": "Dược cục",
    "category": "hospital",
    "pronunciation": "[약국]",
    "created_at": "2026-08-10T02:20:02.677Z"
  },
  {
    "id": "v1-37-의사",
    "ko": "의사",
    "vi": "Bác sĩ",
    "en": "Doctor",
    "level": 1,
    "sinoVi": "Y sư",
    "category": "hospital",
    "pronunciation": "[의사]",
    "created_at": "2026-08-10T02:20:02.677Z"
  },
  {
    "id": "v1-38-약",
    "ko": "약",
    "vi": "Thuốc",
    "en": "Medicine",
    "level": 1,
    "sinoVi": "Dược",
    "category": "hospital",
    "pronunciation": "[약]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-39-버스",
    "ko": "버스",
    "vi": "Xe buýt",
    "en": "Bus",
    "level": 1,
    "sinoVi": "Xa buýt",
    "category": "travel",
    "pronunciation": "[버스]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-40-지하철",
    "ko": "지하철",
    "vi": "Tàu điện ngầm",
    "en": "Subway",
    "level": 1,
    "sinoVi": "Địa hạ thiết",
    "category": "travel",
    "pronunciation": "[지하철]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-41-택시",
    "ko": "택시",
    "vi": "Xe taxi",
    "en": "Taxi",
    "level": 1,
    "sinoVi": "Đặc tây",
    "category": "travel",
    "pronunciation": "[택시]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-42-비행기",
    "ko": "비행기",
    "vi": "Máy bay",
    "en": "Airplane",
    "level": 1,
    "sinoVi": "Phi hành cơ",
    "category": "travel",
    "pronunciation": "[비행기]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-43-공항",
    "ko": "공항",
    "vi": "Sân bay",
    "en": "Airport",
    "level": 1,
    "sinoVi": "Không cảng",
    "category": "travel",
    "pronunciation": "[공항]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-44-한국",
    "ko": "한국",
    "vi": "Hàn Quốc",
    "en": "Korea",
    "level": 1,
    "sinoVi": "Cục",
    "category": "travel",
    "pronunciation": "[한국]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-45-베트남",
    "ko": "베트남",
    "vi": "Việt Nam",
    "en": "Vietnam",
    "level": 1,
    "category": "travel",
    "pronunciation": "[베트남]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-46-오늘",
    "ko": "오늘",
    "vi": "Hôm nay",
    "en": "Today",
    "level": 1,
    "category": "daily",
    "pronunciation": "[오늘]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-47-어제",
    "ko": "어제",
    "vi": "Hôm qua",
    "en": "Yesterday",
    "level": 1,
    "sinoVi": "Tế",
    "category": "daily",
    "pronunciation": "[어제]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-48-내일",
    "ko": "내일",
    "vi": "Ngày mai",
    "en": "Tomorrow",
    "level": 1,
    "category": "daily",
    "pronunciation": "[내일]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-49-주말",
    "ko": "주말",
    "vi": "Cuối tuần",
    "en": "Weekend",
    "level": 1,
    "category": "daily",
    "pronunciation": "[주말]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-50-시간",
    "ko": "시간",
    "vi": "Thời gian / Giờ",
    "en": "Time / Hour",
    "level": 1,
    "sinoVi": "Thị",
    "category": "daily",
    "pronunciation": "[시간]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-51-모자",
    "ko": "모자",
    "vi": "Mũ, Nón",
    "en": "Hat / Cap",
    "level": 1,
    "sinoVi": "Tự",
    "category": "shopping",
    "pronunciation": "[모자]",
    "created_at": "2026-08-10T02:20:02.678Z"
  },
  {
    "id": "v1-52-우산",
    "ko": "우산",
    "vi": "Cái ô, Dù",
    "en": "Umbrella",
    "level": 1,
    "sinoVi": "Sơn",
    "category": "daily",
    "pronunciation": "[우산]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v1-53-볼펜",
    "ko": "볼펜",
    "vi": "Bút bi",
    "en": "Pen",
    "level": 1,
    "category": "academic",
    "pronunciation": "[볼펜]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v1-54-연필",
    "ko": "연필",
    "vi": "Bút chì",
    "en": "Pencil",
    "level": 1,
    "sinoVi": "Nghiên",
    "category": "academic",
    "pronunciation": "[연필]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v1-55-지우개",
    "ko": "지우개",
    "vi": "Cục tẩy",
    "en": "Eraser",
    "level": 1,
    "sinoVi": "Địa",
    "category": "academic",
    "pronunciation": "[지우개]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v1-56-공책",
    "ko": "공책",
    "vi": "Vở ghi",
    "en": "Notebook",
    "level": 1,
    "sinoVi": "Công",
    "category": "academic",
    "pronunciation": "[공책]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v1-57-책상",
    "ko": "책상",
    "vi": "Bàn học",
    "en": "Desk",
    "level": 1,
    "category": "academic",
    "pronunciation": "[책상]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v1-58-의자",
    "ko": "의자",
    "vi": "Cái ghế",
    "en": "Chair",
    "level": 1,
    "sinoVi": "Y Tự",
    "category": "academic",
    "pronunciation": "[의자]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v1-59-문",
    "ko": "문",
    "vi": "Cửa ra vào",
    "en": "Door",
    "level": 1,
    "sinoVi": "Môn",
    "category": "daily",
    "pronunciation": "[문]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v1-60-창문",
    "ko": "창문",
    "vi": "Cửa sổ",
    "en": "Window",
    "level": 1,
    "sinoVi": "Môn",
    "category": "daily",
    "pronunciation": "[창문]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v1-61-안경",
    "ko": "안경",
    "vi": "Kính mắt",
    "en": "Glasses",
    "level": 1,
    "sinoVi": "Kinh",
    "category": "daily",
    "pronunciation": "[안경]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v1-62-거울",
    "ko": "거울",
    "vi": "Cái gương",
    "en": "Mirror",
    "level": 1,
    "category": "daily",
    "pronunciation": "[거울]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v1-63-휴지",
    "ko": "휴지",
    "vi": "Giấy vệ sinh / Giấy ăn",
    "en": "Tissue",
    "level": 1,
    "sinoVi": "Địa",
    "category": "daily",
    "pronunciation": "[휴지]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v1-64-비누",
    "ko": "비누",
    "vi": "Xà phòng",
    "en": "Soap",
    "level": 1,
    "category": "daily",
    "pronunciation": "[비누]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-65-대학교",
    "ko": "대학교",
    "vi": "Trường đại học",
    "en": "University",
    "level": 2,
    "sinoVi": "Đại học hiệu",
    "category": "academic",
    "pronunciation": "[대학교]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-66-전공",
    "ko": "전공",
    "vi": "Chuyên ngành",
    "en": "Major",
    "level": 2,
    "sinoVi": "Chuyên công",
    "category": "academic",
    "pronunciation": "[전공]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-67-수업",
    "ko": "수업",
    "vi": "Giờ học, Bài học",
    "en": "Class / Lesson",
    "level": 2,
    "sinoVi": "Thụ nghiệp",
    "category": "academic",
    "pronunciation": "[수업]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-68-시험",
    "ko": "시험",
    "vi": "Kỳ thi, Bài kiểm tra",
    "en": "Exam / Test",
    "level": 2,
    "sinoVi": "Thí nghiệm",
    "category": "academic",
    "pronunciation": "[시험]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-69-성적",
    "ko": "성적",
    "vi": "Thành tích, Điểm số",
    "en": "Grades / Score",
    "level": 2,
    "sinoVi": "Thành tích",
    "category": "academic",
    "pronunciation": "[성적]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-70-숙제",
    "ko": "숙제",
    "vi": "Bài tập về nhà",
    "en": "Homework",
    "level": 2,
    "sinoVi": "Túc đề",
    "category": "academic",
    "pronunciation": "[숙제]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-71-방학",
    "ko": "방학",
    "vi": "Kỳ nghỉ hè/đông",
    "en": "Vacation (school)",
    "level": 2,
    "sinoVi": "Học",
    "category": "academic",
    "pronunciation": "[방학]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-72-장학금",
    "ko": "장학금",
    "vi": "Học bổng",
    "en": "Scholarship",
    "level": 2,
    "sinoVi": "Tưởng học kim",
    "category": "academic",
    "pronunciation": "[장학금]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-73-은행",
    "ko": "은행",
    "vi": "Ngân hàng",
    "en": "Bank",
    "level": 2,
    "sinoVi": "Ngân hàng",
    "category": "work",
    "pronunciation": "[은행]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-74-통장",
    "ko": "통장",
    "vi": "Sổ tài khoản",
    "en": "Bankbook",
    "level": 2,
    "sinoVi": "Thông trướng",
    "category": "work",
    "pronunciation": "[통장]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-75-비밀번호",
    "ko": "비밀번호",
    "vi": "Mật khẩu",
    "en": "Password / PIN",
    "level": 2,
    "sinoVi": "Bí mật phiên hiệu",
    "category": "work",
    "pronunciation": "[비밀번호]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-76-카카오톡",
    "ko": "카카오톡",
    "vi": "Ứng dụng KakaoTalk",
    "en": "KakaoTalk",
    "level": 2,
    "category": "daily",
    "pronunciation": "[카카오톡]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-77-편의점",
    "ko": "편의점",
    "vi": "Cửa hàng tiện lợi",
    "en": "Convenience store",
    "level": 2,
    "sinoVi": "Y Điếm",
    "category": "shopping",
    "pronunciation": "[편의점]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-78-아르바이트",
    "ko": "아르바이트",
    "vi": "Việc làm thêm (Part-time)",
    "en": "Part-time job",
    "level": 2,
    "category": "work",
    "pronunciation": "[아르바이트]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-79-월세",
    "ko": "월세",
    "vi": "Tiền thuê nhà theo tháng",
    "en": "Monthly rent",
    "level": 2,
    "category": "daily",
    "pronunciation": "[월세]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-80-보증금",
    "ko": "보증금",
    "vi": "Tiền đặt cọc nhà",
    "en": "Deposit money",
    "level": 2,
    "category": "daily",
    "pronunciation": "[보증금]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-81-원룸",
    "ko": "원룸",
    "vi": "Phòng khép kín (One-room)",
    "en": "Studio apartment",
    "level": 2,
    "sinoVi": "Viện",
    "category": "daily",
    "pronunciation": "[원룸]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-82-기숙사",
    "ko": "기숙사",
    "vi": "Ký túc xá",
    "en": "Dormitory",
    "level": 2,
    "sinoVi": "Kế Sư",
    "category": "academic",
    "pronunciation": "[기숙사]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-83-외국인등록증",
    "ko": "외국인등록증",
    "vi": "Thẻ cư trú người nước ngoài",
    "en": "Alien Registration Card",
    "level": 2,
    "sinoVi": "Cục Nhân",
    "category": "work",
    "pronunciation": "[외국인등록증]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-84-여권",
    "ko": "여권",
    "vi": "Hộ chiếu",
    "en": "Passport",
    "level": 2,
    "category": "travel",
    "pronunciation": "[여권]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-85-비자",
    "ko": "비자",
    "vi": "Thị thực (Visa)",
    "en": "Visa",
    "level": 2,
    "sinoVi": "Tự",
    "category": "travel",
    "pronunciation": "[비자]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-86-취업",
    "ko": "취업",
    "vi": "Xin việc, Tìm việc",
    "en": "Employment",
    "level": 2,
    "category": "work",
    "pronunciation": "[취업]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-87-회사원",
    "ko": "회사원",
    "vi": "Nhân viên công ty",
    "en": "Office worker",
    "level": 2,
    "sinoVi": "Sư Viện",
    "category": "work",
    "pronunciation": "[회사원]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-88-월급",
    "ko": "월급",
    "vi": "Lương hàng tháng",
    "en": "Monthly salary",
    "level": 2,
    "sinoVi": "Nguyệt cấp",
    "category": "work",
    "pronunciation": "[월급]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-89-휴가",
    "ko": "휴가",
    "vi": "Kỳ nghỉ làm",
    "en": "Leave / Holiday",
    "level": 2,
    "sinoVi": "Hưu hạ",
    "category": "work",
    "pronunciation": "[휴가]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-90-출근",
    "ko": "출근",
    "vi": "Đi làm",
    "en": "Going to work",
    "level": 2,
    "sinoVi": "Xuất cần",
    "category": "work",
    "pronunciation": "[출근]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-91-퇴근",
    "ko": "퇴근",
    "vi": "Tan làm",
    "en": "Leaving work",
    "level": 2,
    "sinoVi": "Thối cần",
    "category": "work",
    "pronunciation": "[퇴근]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-92-야근",
    "ko": "야근",
    "vi": "Làm tăng ca đêm",
    "en": "Night overtime",
    "level": 2,
    "sinoVi": "Dạ cần",
    "category": "work",
    "pronunciation": "[야근]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-93-간호사",
    "ko": "간호사",
    "vi": "Y tá, Cán hộ sư",
    "en": "Nurse",
    "level": 2,
    "sinoVi": "Cán hộ sư",
    "category": "hospital",
    "pronunciation": "[간호사]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-94-감기",
    "ko": "감기",
    "vi": "Bệnh cảm cúm",
    "en": "Cold / Flu",
    "level": 2,
    "sinoVi": "Kế",
    "category": "hospital",
    "pronunciation": "[감기]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-95-열",
    "ko": "열",
    "vi": "Sốt",
    "en": "Fever",
    "level": 2,
    "category": "hospital",
    "pronunciation": "[열]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-96-기침",
    "ko": "기침",
    "vi": "Ho",
    "en": "Cough",
    "level": 2,
    "sinoVi": "Kế",
    "category": "hospital",
    "pronunciation": "[기침]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-97-주사",
    "ko": "주사",
    "vi": "Tiêm thuốc",
    "en": "Injection",
    "level": 2,
    "sinoVi": "Chú xạ",
    "category": "hospital",
    "pronunciation": "[주사]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-98-처방전",
    "ko": "처방전",
    "vi": "Đơn thuốc",
    "en": "Prescription",
    "level": 2,
    "sinoVi": "Điện",
    "category": "hospital",
    "pronunciation": "[처방전]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v2-99-예약",
    "ko": "예약",
    "vi": "Đặt trước (vấn/phòng)",
    "en": "Reservation",
    "level": 2,
    "sinoVi": "Dự ước",
    "category": "daily",
    "pronunciation": "[예약]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-100-수강신청",
    "ko": "수강신청",
    "vi": "Đăng ký môn học",
    "en": "Course registration",
    "level": 3,
    "sinoVi": "Thủy",
    "category": "academic",
    "pronunciation": "[수강신청]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-101-교양과목",
    "ko": "교양과목",
    "vi": "Môn học đại cương",
    "en": "General elective course",
    "level": 3,
    "sinoVi": "Hiệu",
    "category": "academic",
    "pronunciation": "[교양과목]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-102-전공필수",
    "ko": "전공필수",
    "vi": "Môn chuyên ngành bắt buộc",
    "en": "Required major course",
    "level": 3,
    "sinoVi": "Điện Công Thủy",
    "category": "academic",
    "pronunciation": "[전공필수]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-103-이력서",
    "ko": "이력서",
    "vi": "Sơ yếu lý lịch (CV)",
    "en": "Resume / CV",
    "level": 3,
    "sinoVi": "Lý lịch thư",
    "category": "work",
    "pronunciation": "[이력서]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-104-자기소개서",
    "ko": "자기소개서",
    "vi": "Bài tự giới thiệu bản thân",
    "en": "Cover letter",
    "level": 3,
    "sinoVi": "Tự Kế Thư",
    "category": "work",
    "pronunciation": "[자기소개서]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-105-면접",
    "ko": "면접",
    "vi": "Phỏng vấn",
    "en": "Interview",
    "level": 3,
    "sinoVi": "Diện tiếp",
    "category": "work",
    "pronunciation": "[면접]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-106-합격통지서",
    "ko": "합격통지서",
    "vi": "Giấy báo trúng tuyển",
    "en": "Acceptance letter",
    "level": 3,
    "sinoVi": "Thống Địa Thư",
    "category": "academic",
    "pronunciation": "[합격통지서]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-107-등록금",
    "ko": "등록금",
    "vi": "Học phí",
    "en": "Tuition fee",
    "level": 3,
    "category": "academic",
    "pronunciation": "[등록금]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-108-부동산",
    "ko": "부동산",
    "vi": "Bất động sản / Văn phòng môi giới",
    "en": "Real estate",
    "level": 3,
    "sinoVi": "Bất động sản",
    "category": "daily",
    "pronunciation": "[부동산]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-109-계약서",
    "ko": "계약서",
    "vi": "Hợp đồng",
    "en": "Contract document",
    "level": 3,
    "sinoVi": "Kế Dược Thư",
    "category": "work",
    "pronunciation": "[계약서]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-110-관리비",
    "ko": "관리비",
    "vi": "Phí quản lý nhà",
    "en": "Maintenance fee",
    "level": 3,
    "sinoVi": "Quán Lý",
    "category": "daily",
    "pronunciation": "[관리비]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-111-공과금",
    "ko": "공과금",
    "vi": "Tiền điện nước ga sinh hoạt",
    "en": "Utility bills",
    "level": 3,
    "sinoVi": "Công",
    "category": "daily",
    "pronunciation": "[공과금]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-112-송금",
    "ko": "송금",
    "vi": "Chuyển tiền",
    "en": "Remittance / Money transfer",
    "level": 3,
    "sinoVi": "Tống kim",
    "category": "work",
    "pronunciation": "[송금]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-113-환전",
    "ko": "환전",
    "vi": "Đổi ngoại tệ",
    "en": "Currency exchange",
    "level": 3,
    "sinoVi": "Hoán tiền",
    "category": "travel",
    "pronunciation": "[환전]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-114-건강보험",
    "ko": "건강보험",
    "vi": "Bảo hiểm y tế",
    "en": "Health insurance",
    "level": 3,
    "category": "hospital",
    "pronunciation": "[건강보험]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-115-응급실",
    "ko": "응급실",
    "vi": "Phòng cấp cứu",
    "en": "Emergency room",
    "level": 3,
    "sinoVi": "Ứng cấp thất",
    "category": "hospital",
    "pronunciation": "[응급실]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v3-116-진료비",
    "ko": "진료비",
    "vi": "Phí khám bệnh",
    "en": "Medical treatment fee",
    "level": 3,
    "category": "hospital",
    "pronunciation": "[진료비]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v4-117-승진",
    "ko": "승진",
    "vi": "Thăng tiến, Thăng chức",
    "en": "Promotion",
    "level": 4,
    "sinoVi": "Thăng tiến",
    "category": "work",
    "pronunciation": "[승진]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v4-118-출장",
    "ko": "출장",
    "vi": "Đi công tác",
    "en": "Business trip",
    "level": 4,
    "sinoVi": "Xuất trướng",
    "category": "work",
    "pronunciation": "[출장]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v4-119-보고서",
    "ko": "보고서",
    "vi": "Bản báo cáo",
    "en": "Report document",
    "level": 4,
    "sinoVi": "Báo cáo thư",
    "category": "work",
    "pronunciation": "[보고서]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v4-120-회의",
    "ko": "회의",
    "vi": "Cuộc họp, Hội nghị",
    "en": "Meeting",
    "level": 4,
    "sinoVi": "Hội nghị",
    "category": "work",
    "pronunciation": "[회의]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v4-121-업무",
    "ko": "업무",
    "vi": "Nghiệp vụ, Công việc",
    "en": "Work duty",
    "level": 4,
    "sinoVi": "Nghiệp vụ",
    "category": "work",
    "pronunciation": "[업무]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-122-국제정세",
    "ko": "국제정세",
    "vi": "Tình hình quốc tế",
    "en": "International situation",
    "level": 6,
    "sinoVi": "Quốc tế tình thế",
    "category": "academic",
    "pronunciation": "[국제정세]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-123-지속가능발전",
    "ko": "지속가능발전",
    "vi": "Phát triển bền vững",
    "en": "Sustainable development",
    "level": 6,
    "sinoVi": "Trì tục khả năng phát triển",
    "category": "academic",
    "pronunciation": "[지속가능발전]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-124-빈부격차",
    "ko": "빈부격차",
    "vi": "Khoảng cách giàu nghèo",
    "en": "Gap between rich and poor",
    "level": 6,
    "sinoVi": "Bần phú cách sai",
    "category": "academic",
    "pronunciation": "[빈부격차]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-125-문화유산",
    "ko": "문화유산",
    "vi": "Di sản văn hóa",
    "en": "Cultural heritage",
    "level": 6,
    "sinoVi": "Văn hóa di sản",
    "category": "academic",
    "pronunciation": "[문화유산]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-126-사법개혁",
    "ko": "사법개혁",
    "vi": "Cải cách tư pháp",
    "en": "Judicial reform",
    "level": 6,
    "sinoVi": "Tư pháp cải cách",
    "category": "academic",
    "pronunciation": "[사법개혁]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-127-경제위기",
    "ko": "경제위기",
    "vi": "Khủng hoảng kinh tế",
    "en": "Economic crisis",
    "level": 6,
    "sinoVi": "Kinh tế nguy cơ",
    "category": "academic",
    "pronunciation": "[경제위기]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-128-외교관",
    "ko": "외교관",
    "vi": "Nhà ngoại giao",
    "en": "Diplomat",
    "level": 6,
    "sinoVi": "Ngoại giao quán",
    "category": "academic",
    "pronunciation": "[외교관]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-129-지적재산권",
    "ko": "지적재산권",
    "vi": "Quyền sở hữu trí tuệ",
    "en": "Intellectual property rights",
    "level": 6,
    "sinoVi": "Trí đích tài sản quyền",
    "category": "academic",
    "pronunciation": "[지적재산권]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-130-헌법재판소",
    "ko": "헌법재판소",
    "vi": "Tòa án hiến pháp",
    "en": "Constitutional Court",
    "level": 6,
    "sinoVi": "Hiến pháp tài phán sở",
    "category": "academic",
    "pronunciation": "[헌법재판소]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-131-국회의원",
    "ko": "국회의원",
    "vi": "Nghị sĩ quốc hội",
    "en": "Member of National Assembly",
    "level": 6,
    "sinoVi": "Quốc hội nghị viên",
    "category": "academic",
    "pronunciation": "[국회의원]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-132-민주주의",
    "ko": "민주주의",
    "vi": "Chủ nghĩa dân chủ",
    "en": "Democracy",
    "level": 6,
    "sinoVi": "Dân chủ chủ nghĩa",
    "category": "academic",
    "pronunciation": "[민주주의]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-133-자본주의",
    "ko": "자본주의",
    "vi": "Chủ nghĩa tư bản",
    "en": "Capitalism",
    "level": 6,
    "sinoVi": "Tư bản chủ nghĩa",
    "category": "academic",
    "pronunciation": "[자본주의]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-134-세계화",
    "ko": "세계화",
    "vi": "Toàn cầu hóa",
    "en": "Globalization",
    "level": 6,
    "sinoVi": "Thế giới hóa",
    "category": "academic",
    "pronunciation": "[세계화]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-135-다문화사회",
    "ko": "다문화사회",
    "vi": "Xã hội đa văn hóa",
    "en": "Multicultural society",
    "level": 6,
    "sinoVi": "Đa văn hóa xã hội",
    "category": "academic",
    "pronunciation": "[다문화사회]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-136-초고령사회",
    "ko": "초고령사회",
    "vi": "Xã hội siêu già hóa",
    "en": "Super-aged society",
    "level": 6,
    "sinoVi": "Siêu cao linh xã hội",
    "category": "academic",
    "pronunciation": "[초고령사회]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-137-지구온난화",
    "ko": "지구온난화",
    "vi": "Hiện tượng nóng lên toàn cầu",
    "en": "Global warming",
    "level": 6,
    "sinoVi": "Địa cầu ôn nạn hóa",
    "category": "academic",
    "pronunciation": "[지구온난화]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-138-신재생에너지",
    "ko": "신재생에너지",
    "vi": "Năng lượng tái tạo mới",
    "en": "Renewable energy",
    "level": 6,
    "sinoVi": "Tân tái sinh năng lượng",
    "category": "academic",
    "pronunciation": "[신재생에너지]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-139-인공지능",
    "ko": "인공지능",
    "vi": "Trí tuệ nhân tạo",
    "en": "Artificial intelligence",
    "level": 6,
    "sinoVi": "Nhân công trí năng",
    "category": "academic",
    "pronunciation": "[인공지능]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-140-빅데이터",
    "ko": "빅데이터",
    "vi": "Dữ liệu lớn",
    "en": "Big data",
    "level": 6,
    "sinoVi": "Đại dữ liệu",
    "category": "academic",
    "pronunciation": "[빅데이터]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-141-생명공학",
    "ko": "생명공학",
    "vi": "Công nghệ sinh học",
    "en": "Biotechnology",
    "level": 6,
    "sinoVi": "Sinh mệnh công học",
    "category": "academic",
    "pronunciation": "[생명공학]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-142-우주탐사",
    "ko": "우주탐사",
    "vi": "Thám hiểm vũ trụ",
    "en": "Space exploration",
    "level": 6,
    "sinoVi": "Vũ trụ thám tra",
    "category": "academic",
    "pronunciation": "[우주탐사]",
    "created_at": "2026-08-10T02:20:02.679Z"
  },
  {
    "id": "v6-143-국제통화기금",
    "ko": "국제통화기금",
    "vi": "Quỹ tiền tệ quốc tế (IMF)",
    "en": "International Monetary Fund",
    "level": 6,
    "sinoVi": "Quốc tế thông hóa cơ kim",
    "category": "academic",
    "pronunciation": "[국제통화기금]",
    "created_at": "2026-08-10T02:20:02.679Z"
  }
]
